services:
  test_runner:
    build:
      context: .
      dockerfile: docker/busted.Dockerfile
    volumes: [".:/data"]
    entrypoint: sh -c "busted --verbose /data"
  test_watcher:
    build:
      context: .
      dockerfile: docker/busted.Dockerfile
    volumes: [".:/data"]
    entrypoint: sh -c "find /data -type f | entr -c busted --verbose /data"
    tty: true
  ci-cd:
    build:
      context: .
      dockerfile: docker/nodejs.Dockerfile
    volumes: [".:/app"]
    environment: ["MODE=dev", "TARGET=main"]
    command: node scripts/build.js --env=${MODE} --target=${TARGET}
